sudo: false
language: cpp

matrix:
    include:
        - env: COMPILER_VERSION=4.9
          os: linux
          compiler: g++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
                      - libcppunit-dev

script:
    - bash build.sh
