sudo: required

dist: trusty

language: cpp

compiler:
  - gcc-5

os:
  - linux

script:
  - bash build.sh
    
matrix:
  include:
    - env: GCC_VERSION=5 BUILD_TYPE=Debug CPP=11 ASAN=Off LIBCXX=Off
      os: linux
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - valgrind
          sources:
            - ubuntu-toolchain-r-test

