sudo: false
language: cpp

matrix:
    include:
        - env: COMPILER_VERSION=4.9
          os: linux
          compiler: g++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
                      - libcppunit-dev

        - env: COMPILER_VERSION=3.5
          os: linux
          compiler: clang++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.5
                  packages:
                      - clang-3.5
                     - libcppunit-dev

script:
    - bash build.sh
